// Package graph provides GraphQL types for the metadata-api.
// These types would normally be generated by gqlgen.
// Run `go generate ./...` after installing gqlgen to generate full resolvers.
package graph

import (
	"encoding/json"
	"time"
)

//go:generate go run github.com/99designs/gqlgen generate

// =============================================================================
// CORE TYPES
// =============================================================================

// Health represents the health status.
type Health struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// MetadataDomain represents a domain type.
type MetadataDomain struct {
	Key         string  `json:"key"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	ItemCount   int     `json:"itemCount"`
}

// MetadataRecord represents a metadata record.
type MetadataRecord struct {
	ID        string          `json:"id"`
	ProjectID string          `json:"projectId"`
	Domain    string          `json:"domain"`
	Labels    []string        `json:"labels"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

// MetadataRecordInput is the input for creating/updating a record.
type MetadataRecordInput struct {
	ID        *string         `json:"id,omitempty"`
	ProjectID string          `json:"projectId"`
	Domain    string          `json:"domain"`
	Labels    []string        `json:"labels,omitempty"`
	Payload   json.RawMessage `json:"payload"`
}

// =============================================================================
// ENDPOINT TYPES
// =============================================================================

// MetadataEndpoint represents an endpoint.
type MetadataEndpoint struct {
	ID                 string          `json:"id"`
	SourceID           string          `json:"sourceId"`
	ProjectID          *string         `json:"projectId,omitempty"`
	Name               string          `json:"name"`
	Description        *string         `json:"description,omitempty"`
	Verb               string          `json:"verb"`
	URL                string          `json:"url"`
	AuthPolicy         *string         `json:"authPolicy,omitempty"`
	Domain             *string         `json:"domain,omitempty"`
	Labels             []string        `json:"labels,omitempty"`
	Config             json.RawMessage `json:"config,omitempty"`
	DetectedVersion    *string         `json:"detectedVersion,omitempty"`
	VersionHint        *string         `json:"versionHint,omitempty"`
	Capabilities       []string        `json:"capabilities,omitempty"`
	DelegatedConnected *bool           `json:"delegatedConnected,omitempty"`
	CreatedAt          *time.Time      `json:"createdAt,omitempty"`
	UpdatedAt          *time.Time      `json:"updatedAt,omitempty"`
	DeletedAt          *time.Time      `json:"deletedAt,omitempty"`
	DeletionReason     *string         `json:"deletionReason,omitempty"`
	IsDeleted          bool            `json:"isDeleted"`
}

// MetadataEndpointInput is the input for registering an endpoint.
type MetadataEndpointInput struct {
	ID          *string         `json:"id,omitempty"`
	SourceID    *string         `json:"sourceId,omitempty"`
	ProjectID   *string         `json:"projectId,omitempty"`
	Name        string          `json:"name"`
	Description *string         `json:"description,omitempty"`
	Verb        *string         `json:"verb,omitempty"`
	URL         *string         `json:"url,omitempty"`
	AuthPolicy  *string         `json:"authPolicy,omitempty"`
	Domain      *string         `json:"domain,omitempty"`
	Labels      []string        `json:"labels,omitempty"`
	Config      json.RawMessage `json:"config,omitempty"`
}

// =============================================================================
// INTERFACES FOR RESOLVERS
// =============================================================================

// QueryResolver interface for query resolvers.
type QueryResolver interface {
	Health(ctx interface{}) (*Health, error)
	MetadataEndpoints(ctx interface{}, projectID *string, includeDeleted *bool) ([]*MetadataEndpoint, error)
	MetadataEndpoint(ctx interface{}, id string) (*MetadataEndpoint, error)
	Endpoint(ctx interface{}, id string) (*MetadataEndpoint, error)
	EndpointBySourceID(ctx interface{}, sourceID string) (*MetadataEndpoint, error)
	MetadataRecords(ctx interface{}, domain string, projectID *string, labels []string, search *string, limit *int) ([]*MetadataRecord, error)
}

// MutationResolver interface for mutation resolvers.
type MutationResolver interface {
	UpsertMetadataRecord(ctx interface{}, input MetadataRecordInput) (*MetadataRecord, error)
	RegisterMetadataEndpoint(ctx interface{}, input MetadataEndpointInput) (*MetadataEndpoint, error)
	DeleteMetadataEndpoint(ctx interface{}, id string, reason *string) (*MetadataEndpoint, error)
}
