package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"time"

	"github.com/nucleus/metadata-api/graph/model"
	"github.com/nucleus/metadata-api/internal/database"
)

// ProjectID is the resolver for the projectId field.
func (r *graphEdgeResolver) ProjectID(ctx context.Context, obj *database.GraphEdge) (*string, error) {
	panic(fmt.Errorf("not implemented: ProjectID - projectId"))
}

// Confidence is the resolver for the confidence field.
func (r *graphEdgeResolver) Confidence(ctx context.Context, obj *database.GraphEdge) (*float64, error) {
	panic(fmt.Errorf("not implemented: Confidence - confidence"))
}

// SpecRef is the resolver for the specRef field.
func (r *graphEdgeResolver) SpecRef(ctx context.Context, obj *database.GraphEdge) (*string, error) {
	panic(fmt.Errorf("not implemented: SpecRef - specRef"))
}

// Metadata is the resolver for the metadata field.
func (r *graphEdgeResolver) Metadata(ctx context.Context, obj *database.GraphEdge) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// Scope is the resolver for the scope field.
func (r *graphEdgeResolver) Scope(ctx context.Context, obj *database.GraphEdge) (*database.GraphScope, error) {
	panic(fmt.Errorf("not implemented: Scope - scope"))
}

// Identity is the resolver for the identity field.
func (r *graphEdgeResolver) Identity(ctx context.Context, obj *database.GraphEdge) (*database.GraphIdentity, error) {
	panic(fmt.Errorf("not implemented: Identity - identity"))
}

// ExternalID is the resolver for the externalId field.
func (r *graphIdentityResolver) ExternalID(ctx context.Context, obj *database.GraphIdentity) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: ExternalID - externalId"))
}

// Provenance is the resolver for the provenance field.
func (r *graphIdentityResolver) Provenance(ctx context.Context, obj *database.GraphIdentity) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Provenance - provenance"))
}

// ProjectID is the resolver for the projectId field.
func (r *graphNodeResolver) ProjectID(ctx context.Context, obj *database.GraphNode) (*string, error) {
	panic(fmt.Errorf("not implemented: ProjectID - projectId"))
}

// CanonicalPath is the resolver for the canonicalPath field.
func (r *graphNodeResolver) CanonicalPath(ctx context.Context, obj *database.GraphNode) (*string, error) {
	panic(fmt.Errorf("not implemented: CanonicalPath - canonicalPath"))
}

// SourceSystem is the resolver for the sourceSystem field.
func (r *graphNodeResolver) SourceSystem(ctx context.Context, obj *database.GraphNode) (*string, error) {
	panic(fmt.Errorf("not implemented: SourceSystem - sourceSystem"))
}

// SpecRef is the resolver for the specRef field.
func (r *graphNodeResolver) SpecRef(ctx context.Context, obj *database.GraphNode) (*string, error) {
	panic(fmt.Errorf("not implemented: SpecRef - specRef"))
}

// Properties is the resolver for the properties field.
func (r *graphNodeResolver) Properties(ctx context.Context, obj *database.GraphNode) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Properties - properties"))
}

// Phase is the resolver for the phase field.
func (r *graphNodeResolver) Phase(ctx context.Context, obj *database.GraphNode) (*string, error) {
	panic(fmt.Errorf("not implemented: Phase - phase"))
}

// Scope is the resolver for the scope field.
func (r *graphNodeResolver) Scope(ctx context.Context, obj *database.GraphNode) (*database.GraphScope, error) {
	panic(fmt.Errorf("not implemented: Scope - scope"))
}

// Identity is the resolver for the identity field.
func (r *graphNodeResolver) Identity(ctx context.Context, obj *database.GraphNode) (*database.GraphIdentity, error) {
	panic(fmt.Errorf("not implemented: Identity - identity"))
}

// Provenance is the resolver for the provenance field.
func (r *graphNodeResolver) Provenance(ctx context.Context, obj *database.GraphNode) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Provenance - provenance"))
}

// SinkEndpointID is the resolver for the sinkEndpointId field.
func (r *ingestionUnitConfigResolver) SinkEndpointID(ctx context.Context, obj *database.IngestionUnitConfig) (*string, error) {
	panic(fmt.Errorf("not implemented: SinkEndpointID - sinkEndpointId"))
}

// ScheduleIntervalMinutes is the resolver for the scheduleIntervalMinutes field.
func (r *ingestionUnitConfigResolver) ScheduleIntervalMinutes(ctx context.Context, obj *database.IngestionUnitConfig) (*int, error) {
	panic(fmt.Errorf("not implemented: ScheduleIntervalMinutes - scheduleIntervalMinutes"))
}

// Policy is the resolver for the policy field.
func (r *ingestionUnitConfigResolver) Policy(ctx context.Context, obj *database.IngestionUnitConfig) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Policy - policy"))
}

// LastStatus is the resolver for the lastStatus field.
func (r *ingestionUnitConfigResolver) LastStatus(ctx context.Context, obj *database.IngestionUnitConfig) (*model.IngestionStatus, error) {
	panic(fmt.Errorf("not implemented: LastStatus - lastStatus"))
}

// Endpoint is the resolver for the endpoint field.
func (r *metadataCollectionResolver) Endpoint(ctx context.Context, obj *database.MetadataCollection) (*database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: Endpoint - endpoint"))
}

// ScheduleCron is the resolver for the scheduleCron field.
func (r *metadataCollectionResolver) ScheduleCron(ctx context.Context, obj *database.MetadataCollection) (*string, error) {
	panic(fmt.Errorf("not implemented: ScheduleCron - scheduleCron"))
}

// TemporalScheduleID is the resolver for the temporalScheduleId field.
func (r *metadataCollectionResolver) TemporalScheduleID(ctx context.Context, obj *database.MetadataCollection) (*string, error) {
	panic(fmt.Errorf("not implemented: TemporalScheduleID - temporalScheduleId"))
}

// Runs is the resolver for the runs field.
func (r *metadataCollectionResolver) Runs(ctx context.Context, obj *database.MetadataCollection, first *int, after *string) ([]database.MetadataCollectionRun, error) {
	panic(fmt.Errorf("not implemented: Runs - runs"))
}

// CollectionID is the resolver for the collectionId field.
func (r *metadataCollectionRunResolver) CollectionID(ctx context.Context, obj *database.MetadataCollectionRun) (*string, error) {
	panic(fmt.Errorf("not implemented: CollectionID - collectionId"))
}

// Collection is the resolver for the collection field.
func (r *metadataCollectionRunResolver) Collection(ctx context.Context, obj *database.MetadataCollectionRun) (*database.MetadataCollection, error) {
	panic(fmt.Errorf("not implemented: Collection - collection"))
}

// Endpoint is the resolver for the endpoint field.
func (r *metadataCollectionRunResolver) Endpoint(ctx context.Context, obj *database.MetadataCollectionRun) (*database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: Endpoint - endpoint"))
}

// Status is the resolver for the status field.
func (r *metadataCollectionRunResolver) Status(ctx context.Context, obj *database.MetadataCollectionRun) (model.MetadataCollectionStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// RequestedBy is the resolver for the requestedBy field.
func (r *metadataCollectionRunResolver) RequestedBy(ctx context.Context, obj *database.MetadataCollectionRun) (*string, error) {
	panic(fmt.Errorf("not implemented: RequestedBy - requestedBy"))
}

// StartedAt is the resolver for the startedAt field.
func (r *metadataCollectionRunResolver) StartedAt(ctx context.Context, obj *database.MetadataCollectionRun) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: StartedAt - startedAt"))
}

// CompletedAt is the resolver for the completedAt field.
func (r *metadataCollectionRunResolver) CompletedAt(ctx context.Context, obj *database.MetadataCollectionRun) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CompletedAt - completedAt"))
}

// WorkflowID is the resolver for the workflowId field.
func (r *metadataCollectionRunResolver) WorkflowID(ctx context.Context, obj *database.MetadataCollectionRun) (*string, error) {
	panic(fmt.Errorf("not implemented: WorkflowID - workflowId"))
}

// TemporalRunID is the resolver for the temporalRunId field.
func (r *metadataCollectionRunResolver) TemporalRunID(ctx context.Context, obj *database.MetadataCollectionRun) (*string, error) {
	panic(fmt.Errorf("not implemented: TemporalRunID - temporalRunId"))
}

// Error is the resolver for the error field.
func (r *metadataCollectionRunResolver) Error(ctx context.Context, obj *database.MetadataCollectionRun) (*string, error) {
	panic(fmt.Errorf("not implemented: Error - error"))
}

// Filters is the resolver for the filters field.
func (r *metadataCollectionRunResolver) Filters(ctx context.Context, obj *database.MetadataCollectionRun) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Filters - filters"))
}

// SourceID is the resolver for the sourceId field.
func (r *metadataEndpointResolver) SourceID(ctx context.Context, obj *database.MetadataEndpoint) (string, error) {
	panic(fmt.Errorf("not implemented: SourceID - sourceId"))
}

// ProjectID is the resolver for the projectId field.
func (r *metadataEndpointResolver) ProjectID(ctx context.Context, obj *database.MetadataEndpoint) (*string, error) {
	panic(fmt.Errorf("not implemented: ProjectID - projectId"))
}

// Description is the resolver for the description field.
func (r *metadataEndpointResolver) Description(ctx context.Context, obj *database.MetadataEndpoint) (*string, error) {
	panic(fmt.Errorf("not implemented: Description - description"))
}

// AuthPolicy is the resolver for the authPolicy field.
func (r *metadataEndpointResolver) AuthPolicy(ctx context.Context, obj *database.MetadataEndpoint) (*string, error) {
	panic(fmt.Errorf("not implemented: AuthPolicy - authPolicy"))
}

// Domain is the resolver for the domain field.
func (r *metadataEndpointResolver) Domain(ctx context.Context, obj *database.MetadataEndpoint) (*string, error) {
	panic(fmt.Errorf("not implemented: Domain - domain"))
}

// Config is the resolver for the config field.
func (r *metadataEndpointResolver) Config(ctx context.Context, obj *database.MetadataEndpoint) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Config - config"))
}

// DetectedVersion is the resolver for the detectedVersion field.
func (r *metadataEndpointResolver) DetectedVersion(ctx context.Context, obj *database.MetadataEndpoint) (*string, error) {
	panic(fmt.Errorf("not implemented: DetectedVersion - detectedVersion"))
}

// VersionHint is the resolver for the versionHint field.
func (r *metadataEndpointResolver) VersionHint(ctx context.Context, obj *database.MetadataEndpoint) (*string, error) {
	panic(fmt.Errorf("not implemented: VersionHint - versionHint"))
}

// DeletedAt is the resolver for the deletedAt field.
func (r *metadataEndpointResolver) DeletedAt(ctx context.Context, obj *database.MetadataEndpoint) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: DeletedAt - deletedAt"))
}

// DeletionReason is the resolver for the deletionReason field.
func (r *metadataEndpointResolver) DeletionReason(ctx context.Context, obj *database.MetadataEndpoint) (*string, error) {
	panic(fmt.Errorf("not implemented: DeletionReason - deletionReason"))
}

// IsDeleted is the resolver for the isDeleted field.
func (r *metadataEndpointResolver) IsDeleted(ctx context.Context, obj *database.MetadataEndpoint) (bool, error) {
	panic(fmt.Errorf("not implemented: IsDeleted - isDeleted"))
}

// Runs is the resolver for the runs field.
func (r *metadataEndpointResolver) Runs(ctx context.Context, obj *database.MetadataEndpoint, limit *int) ([]database.MetadataCollectionRun, error) {
	panic(fmt.Errorf("not implemented: Runs - runs"))
}

// Datasets is the resolver for the datasets field.
func (r *metadataEndpointResolver) Datasets(ctx context.Context, obj *database.MetadataEndpoint, limit *int, search *string) ([]model.CatalogDataset, error) {
	panic(fmt.Errorf("not implemented: Datasets - datasets"))
}

// Payload is the resolver for the payload field.
func (r *metadataRecordResolver) Payload(ctx context.Context, obj *database.MetadataRecord) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Payload - payload"))
}

// UpsertMetadataRecord is the resolver for the upsertMetadataRecord field.
func (r *mutationResolver) UpsertMetadataRecord(ctx context.Context, input model.MetadataRecordInput) (*database.MetadataRecord, error) {
	panic(fmt.Errorf("not implemented: UpsertMetadataRecord - upsertMetadataRecord"))
}

// RegisterMetadataEndpoint is the resolver for the registerMetadataEndpoint field.
func (r *mutationResolver) RegisterMetadataEndpoint(ctx context.Context, input model.MetadataEndpointInput) (*database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: RegisterMetadataEndpoint - registerMetadataEndpoint"))
}

// DeleteMetadataEndpoint is the resolver for the deleteMetadataEndpoint field.
func (r *mutationResolver) DeleteMetadataEndpoint(ctx context.Context, id string, reason *string) (*database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: DeleteMetadataEndpoint - deleteMetadataEndpoint"))
}

// RegisterEndpoint is the resolver for the registerEndpoint field.
func (r *mutationResolver) RegisterEndpoint(ctx context.Context, input model.EndpointInput) (*database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: RegisterEndpoint - registerEndpoint"))
}

// UpdateEndpoint is the resolver for the updateEndpoint field.
func (r *mutationResolver) UpdateEndpoint(ctx context.Context, id string, patch model.EndpointPatch) (*database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: UpdateEndpoint - updateEndpoint"))
}

// DeleteEndpoint is the resolver for the deleteEndpoint field.
func (r *mutationResolver) DeleteEndpoint(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteEndpoint - deleteEndpoint"))
}

// TestMetadataEndpoint is the resolver for the testMetadataEndpoint field.
func (r *mutationResolver) TestMetadataEndpoint(ctx context.Context, input model.MetadataEndpointInput) (*model.MetadataEndpointTestResult, error) {
	panic(fmt.Errorf("not implemented: TestMetadataEndpoint - testMetadataEndpoint"))
}

// TestEndpoint is the resolver for the testEndpoint field.
func (r *mutationResolver) TestEndpoint(ctx context.Context, input model.TestEndpointInput) (*model.TestResult, error) {
	panic(fmt.Errorf("not implemented: TestEndpoint - testEndpoint"))
}

// StartOneDriveAuth is the resolver for the startOneDriveAuth field.
func (r *mutationResolver) StartOneDriveAuth(ctx context.Context, endpointID string) (*database.OneDriveAuthSession, error) {
	panic(fmt.Errorf("not implemented: StartOneDriveAuth - startOneDriveAuth"))
}

// CompleteOneDriveAuth is the resolver for the completeOneDriveAuth field.
func (r *mutationResolver) CompleteOneDriveAuth(ctx context.Context, state string, code *string) (*model.OneDriveAuthResult, error) {
	panic(fmt.Errorf("not implemented: CompleteOneDriveAuth - completeOneDriveAuth"))
}

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, input model.CollectionCreateInput) (*database.MetadataCollection, error) {
	panic(fmt.Errorf("not implemented: CreateCollection - createCollection"))
}

// UpdateCollection is the resolver for the updateCollection field.
func (r *mutationResolver) UpdateCollection(ctx context.Context, id string, input model.CollectionUpdateInput) (*database.MetadataCollection, error) {
	panic(fmt.Errorf("not implemented: UpdateCollection - updateCollection"))
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteCollection - deleteCollection"))
}

// TriggerCollection is the resolver for the triggerCollection field.
func (r *mutationResolver) TriggerCollection(ctx context.Context, collectionID string, filters map[string]any, schemaOverride []string) (*database.MetadataCollectionRun, error) {
	panic(fmt.Errorf("not implemented: TriggerCollection - triggerCollection"))
}

// TriggerEndpointCollection is the resolver for the triggerEndpointCollection field.
func (r *mutationResolver) TriggerEndpointCollection(ctx context.Context, endpointID string, filters map[string]any, schemaOverride []string) (*database.MetadataCollectionRun, error) {
	panic(fmt.Errorf("not implemented: TriggerEndpointCollection - triggerEndpointCollection"))
}

// TriggerMetadataCollection is the resolver for the triggerMetadataCollection field.
func (r *mutationResolver) TriggerMetadataCollection(ctx context.Context, input model.MetadataCollectionRequestInput) (*database.MetadataCollectionRun, error) {
	panic(fmt.Errorf("not implemented: TriggerMetadataCollection - triggerMetadataCollection"))
}

// PreviewMetadataDataset is the resolver for the previewMetadataDataset field.
func (r *mutationResolver) PreviewMetadataDataset(ctx context.Context, id string, limit *int) (*model.CatalogDatasetPreview, error) {
	panic(fmt.Errorf("not implemented: PreviewMetadataDataset - previewMetadataDataset"))
}

// StartIngestion is the resolver for the startIngestion field.
func (r *mutationResolver) StartIngestion(ctx context.Context, endpointID string, unitID string, sinkID *string, sinkEndpointID *string) (*model.IngestionActionResult, error) {
	panic(fmt.Errorf("not implemented: StartIngestion - startIngestion"))
}

// PauseIngestion is the resolver for the pauseIngestion field.
func (r *mutationResolver) PauseIngestion(ctx context.Context, endpointID string, unitID string, sinkID *string) (*model.IngestionActionResult, error) {
	panic(fmt.Errorf("not implemented: PauseIngestion - pauseIngestion"))
}

// ResetIngestionCheckpoint is the resolver for the resetIngestionCheckpoint field.
func (r *mutationResolver) ResetIngestionCheckpoint(ctx context.Context, endpointID string, unitID string, sinkID *string) (*model.IngestionActionResult, error) {
	panic(fmt.Errorf("not implemented: ResetIngestionCheckpoint - resetIngestionCheckpoint"))
}

// ConfigureIngestionUnit is the resolver for the configureIngestionUnit field.
func (r *mutationResolver) ConfigureIngestionUnit(ctx context.Context, input model.IngestionUnitConfigInput) (*database.IngestionUnitConfig, error) {
	panic(fmt.Errorf("not implemented: ConfigureIngestionUnit - configureIngestionUnit"))
}

// AuthSessionID is the resolver for the authSessionId field.
func (r *oneDriveAuthSessionResolver) AuthSessionID(ctx context.Context, obj *database.OneDriveAuthSession) (string, error) {
	panic(fmt.Errorf("not implemented: AuthSessionID - authSessionId"))
}

// AuthURL is the resolver for the authUrl field.
func (r *oneDriveAuthSessionResolver) AuthURL(ctx context.Context, obj *database.OneDriveAuthSession) (string, error) {
	panic(fmt.Errorf("not implemented: AuthURL - authUrl"))
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// MetadataDomains is the resolver for the metadataDomains field.
func (r *queryResolver) MetadataDomains(ctx context.Context) ([]model.MetadataDomain, error) {
	panic(fmt.Errorf("not implemented: MetadataDomains - metadataDomains"))
}

// MetadataRecords is the resolver for the metadataRecords field.
func (r *queryResolver) MetadataRecords(ctx context.Context, domain string, projectID *string, labels []string, search *string, limit *int) ([]database.MetadataRecord, error) {
	panic(fmt.Errorf("not implemented: MetadataRecords - metadataRecords"))
}

// GraphNodes is the resolver for the graphNodes field.
func (r *queryResolver) GraphNodes(ctx context.Context, filter *model.GraphNodeFilter) ([]database.GraphNode, error) {
	panic(fmt.Errorf("not implemented: GraphNodes - graphNodes"))
}

// GraphEdges is the resolver for the graphEdges field.
func (r *queryResolver) GraphEdges(ctx context.Context, filter *model.GraphEdgeFilter) ([]database.GraphEdge, error) {
	panic(fmt.Errorf("not implemented: GraphEdges - graphEdges"))
}

// KbNodes is the resolver for the kbNodes field.
func (r *queryResolver) KbNodes(ctx context.Context, typeArg *string, scope *model.GraphScopeInput, search *string, first *int, after *string) (*model.KbNodeConnection, error) {
	panic(fmt.Errorf("not implemented: KbNodes - kbNodes"))
}

// KbEdges is the resolver for the kbEdges field.
func (r *queryResolver) KbEdges(ctx context.Context, edgeType *string, edgeTypes []string, direction *model.GraphEdgeDirection, scope *model.GraphScopeInput, sourceID *string, targetID *string, first *int, after *string) (*model.KbEdgeConnection, error) {
	panic(fmt.Errorf("not implemented: KbEdges - kbEdges"))
}

// KbNode is the resolver for the kbNode field.
func (r *queryResolver) KbNode(ctx context.Context, id string) (*database.GraphNode, error) {
	panic(fmt.Errorf("not implemented: KbNode - kbNode"))
}

// KbNeighbors is the resolver for the kbNeighbors field.
func (r *queryResolver) KbNeighbors(ctx context.Context, id string, edgeTypes []string, depth *int, limit *int) (*model.KbScene, error) {
	panic(fmt.Errorf("not implemented: KbNeighbors - kbNeighbors"))
}

// KbScene is the resolver for the kbScene field.
func (r *queryResolver) KbScene(ctx context.Context, id string, edgeTypes []string, depth *int, limit *int) (*model.KbScene, error) {
	panic(fmt.Errorf("not implemented: KbScene - kbScene"))
}

// KbFacets is the resolver for the kbFacets field.
func (r *queryResolver) KbFacets(ctx context.Context, scope *model.GraphScopeInput) (*model.KbFacets, error) {
	panic(fmt.Errorf("not implemented: KbFacets - kbFacets"))
}

// KbMeta is the resolver for the kbMeta field.
func (r *queryResolver) KbMeta(ctx context.Context, scope *model.GraphScopeInput) (*model.KbMeta, error) {
	panic(fmt.Errorf("not implemented: KbMeta - kbMeta"))
}

// MetadataEndpoints is the resolver for the metadataEndpoints field.
func (r *queryResolver) MetadataEndpoints(ctx context.Context, projectID *string, includeDeleted *bool) ([]database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: MetadataEndpoints - metadataEndpoints"))
}

// MetadataEndpoint is the resolver for the metadataEndpoint field.
func (r *queryResolver) MetadataEndpoint(ctx context.Context, id string) (*database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: MetadataEndpoint - metadataEndpoint"))
}

// Endpoints is the resolver for the endpoints field.
func (r *queryResolver) Endpoints(ctx context.Context, projectSlug *string, capability *string, search *string, first *int, after *string) ([]database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: Endpoints - endpoints"))
}

// Endpoint is the resolver for the endpoint field.
func (r *queryResolver) Endpoint(ctx context.Context, id string) (*database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: Endpoint - endpoint"))
}

// EndpointBySourceID is the resolver for the endpointBySourceId field.
func (r *queryResolver) EndpointBySourceID(ctx context.Context, sourceID string) (*database.MetadataEndpoint, error) {
	panic(fmt.Errorf("not implemented: EndpointBySourceID - endpointBySourceId"))
}

// EndpointTemplates is the resolver for the endpointTemplates field.
func (r *queryResolver) EndpointTemplates(ctx context.Context, family *model.MetadataEndpointFamily) ([]model.MetadataEndpointTemplate, error) {
	panic(fmt.Errorf("not implemented: EndpointTemplates - endpointTemplates"))
}

// MetadataEndpointTemplates is the resolver for the metadataEndpointTemplates field.
func (r *queryResolver) MetadataEndpointTemplates(ctx context.Context, family *model.MetadataEndpointFamily) ([]model.MetadataEndpointTemplate, error) {
	panic(fmt.Errorf("not implemented: MetadataEndpointTemplates - metadataEndpointTemplates"))
}

// Collections is the resolver for the collections field.
func (r *queryResolver) Collections(ctx context.Context, endpointID *string, isEnabled *bool, first *int, after *string) ([]database.MetadataCollection, error) {
	panic(fmt.Errorf("not implemented: Collections - collections"))
}

// Collection is the resolver for the collection field.
func (r *queryResolver) Collection(ctx context.Context, id string) (*database.MetadataCollection, error) {
	panic(fmt.Errorf("not implemented: Collection - collection"))
}

// CollectionRuns is the resolver for the collectionRuns field.
func (r *queryResolver) CollectionRuns(ctx context.Context, filter *model.MetadataCollectionRunFilter, first *int, after *string) ([]database.MetadataCollectionRun, error) {
	panic(fmt.Errorf("not implemented: CollectionRuns - collectionRuns"))
}

// MetadataCollectionRuns is the resolver for the metadataCollectionRuns field.
func (r *queryResolver) MetadataCollectionRuns(ctx context.Context, filter *model.MetadataCollectionRunFilter, limit *int) ([]database.MetadataCollectionRun, error) {
	panic(fmt.Errorf("not implemented: MetadataCollectionRuns - metadataCollectionRuns"))
}

// CatalogDatasets is the resolver for the catalogDatasets field.
func (r *queryResolver) CatalogDatasets(ctx context.Context, projectID *string, labels []string, search *string, endpointID *string, unlabeledOnly *bool) ([]model.CatalogDataset, error) {
	panic(fmt.Errorf("not implemented: CatalogDatasets - catalogDatasets"))
}

// CatalogDatasetConnection is the resolver for the catalogDatasetConnection field.
func (r *queryResolver) CatalogDatasetConnection(ctx context.Context, projectID *string, labels []string, search *string, endpointID *string, unlabeledOnly *bool, first *int, after *string) (*model.CatalogDatasetConnection, error) {
	panic(fmt.Errorf("not implemented: CatalogDatasetConnection - catalogDatasetConnection"))
}

// CatalogDatasetPreview is the resolver for the catalogDatasetPreview field.
func (r *queryResolver) CatalogDatasetPreview(ctx context.Context, id string) (*model.CatalogDatasetPreview, error) {
	panic(fmt.Errorf("not implemented: CatalogDatasetPreview - catalogDatasetPreview"))
}

// MetadataDataset is the resolver for the metadataDataset field.
func (r *queryResolver) MetadataDataset(ctx context.Context, id string) (*model.CatalogDataset, error) {
	panic(fmt.Errorf("not implemented: MetadataDataset - metadataDataset"))
}

// EndpointDatasets is the resolver for the endpointDatasets field.
func (r *queryResolver) EndpointDatasets(ctx context.Context, endpointID string, domain *string, projectSlug *string, first *int, after *string) ([]database.MetadataRecord, error) {
	panic(fmt.Errorf("not implemented: EndpointDatasets - endpointDatasets"))
}

// IngestionUnits is the resolver for the ingestionUnits field.
func (r *queryResolver) IngestionUnits(ctx context.Context, endpointID string) ([]model.IngestionUnit, error) {
	panic(fmt.Errorf("not implemented: IngestionUnits - ingestionUnits"))
}

// IngestionSinks is the resolver for the ingestionSinks field.
func (r *queryResolver) IngestionSinks(ctx context.Context) ([]model.IngestionSink, error) {
	panic(fmt.Errorf("not implemented: IngestionSinks - ingestionSinks"))
}

// IngestionStatuses is the resolver for the ingestionStatuses field.
func (r *queryResolver) IngestionStatuses(ctx context.Context, endpointID string) ([]model.IngestionStatus, error) {
	panic(fmt.Errorf("not implemented: IngestionStatuses - ingestionStatuses"))
}

// IngestionStatus is the resolver for the ingestionStatus field.
func (r *queryResolver) IngestionStatus(ctx context.Context, endpointID string, unitID string) (*model.IngestionStatus, error) {
	panic(fmt.Errorf("not implemented: IngestionStatus - ingestionStatus"))
}

// IngestionUnitConfigs is the resolver for the ingestionUnitConfigs field.
func (r *queryResolver) IngestionUnitConfigs(ctx context.Context, endpointID string) ([]database.IngestionUnitConfig, error) {
	panic(fmt.Errorf("not implemented: IngestionUnitConfigs - ingestionUnitConfigs"))
}

// GraphEdge returns GraphEdgeResolver implementation.
func (r *Resolver) GraphEdge() GraphEdgeResolver { return &graphEdgeResolver{r} }

// GraphIdentity returns GraphIdentityResolver implementation.
func (r *Resolver) GraphIdentity() GraphIdentityResolver { return &graphIdentityResolver{r} }

// GraphNode returns GraphNodeResolver implementation.
func (r *Resolver) GraphNode() GraphNodeResolver { return &graphNodeResolver{r} }

// IngestionUnitConfig returns IngestionUnitConfigResolver implementation.
func (r *Resolver) IngestionUnitConfig() IngestionUnitConfigResolver {
	return &ingestionUnitConfigResolver{r}
}

// MetadataCollection returns MetadataCollectionResolver implementation.
func (r *Resolver) MetadataCollection() MetadataCollectionResolver {
	return &metadataCollectionResolver{r}
}

// MetadataCollectionRun returns MetadataCollectionRunResolver implementation.
func (r *Resolver) MetadataCollectionRun() MetadataCollectionRunResolver {
	return &metadataCollectionRunResolver{r}
}

// MetadataEndpoint returns MetadataEndpointResolver implementation.
func (r *Resolver) MetadataEndpoint() MetadataEndpointResolver { return &metadataEndpointResolver{r} }

// MetadataRecord returns MetadataRecordResolver implementation.
func (r *Resolver) MetadataRecord() MetadataRecordResolver { return &metadataRecordResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// OneDriveAuthSession returns OneDriveAuthSessionResolver implementation.
func (r *Resolver) OneDriveAuthSession() OneDriveAuthSessionResolver {
	return &oneDriveAuthSessionResolver{r}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type graphEdgeResolver struct{ *Resolver }
type graphIdentityResolver struct{ *Resolver }
type graphNodeResolver struct{ *Resolver }
type ingestionUnitConfigResolver struct{ *Resolver }
type metadataCollectionResolver struct{ *Resolver }
type metadataCollectionRunResolver struct{ *Resolver }
type metadataEndpointResolver struct{ *Resolver }
type metadataRecordResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type oneDriveAuthSessionResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
