from __future__ import annotations

from typing import Any, Dict

JIRA_API_LIBRARY: Dict[str, Dict[str, str]] = {
    "project_search": {
        "method": "GET",
        "path": "/rest/api/3/project/search",
        "description": "List projects visible to the authenticated user",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-projects/#api-rest-api-3-project-search-get",
        "scope": "projects",
    },
    "project_detail": {
        "method": "GET",
        "path": "/rest/api/3/project/{projectIdOrKey}",
        "description": "Fetch project metadata and configuration",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-projects/#api-rest-api-3-project-projectidorkey-get",
        "scope": "projects",
    },
    "project_roles": {
        "method": "GET",
        "path": "/rest/api/3/project/{projectIdOrKey}/role",
        "description": "Enumerate project roles",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-project-roles/#api-rest-api-3-project-projectidorkey-role-get",
        "scope": "projects",
    },
    "project_components": {
        "method": "GET",
        "path": "/rest/api/3/project/{projectIdOrKey}/component",
        "description": "List project components",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-components/#api-rest-api-3-project-projectidorkey-component-get",
        "scope": "projects",
    },
    "issue_search": {
        "method": "GET",
        "path": "/rest/api/3/search",
        "description": "Search issues via JQL with pagination",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/#api-rest-api-3-search-get",
        "scope": "issues",
    },
    "issue_detail": {
        "method": "GET",
        "path": "/rest/api/3/issue/{issueIdOrKey}",
        "description": "Retrieve a single issue with selected fields",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-get",
        "scope": "issues",
    },
    "issue_transitions": {
        "method": "GET",
        "path": "/rest/api/3/issue/{issueIdOrKey}/transitions",
        "description": "List allowed transitions for an issue",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-workflow/#api-rest-api-3-issue-issueidorkey-transitions-get",
        "scope": "issues",
    },
    "field_catalog": {
        "method": "GET",
        "path": "/rest/api/3/field",
        "description": "Enumerate built-in and custom fields",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-fields/#api-rest-api-3-field-get",
        "scope": "issues",
    },
    "user_search": {
        "method": "GET",
        "path": "/rest/api/3/user/search",
        "description": "Search users by query",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-users/#api-rest-api-3-user-search-get",
        "scope": "users",
    },
    "user_detail": {
        "method": "GET",
        "path": "/rest/api/3/user",
        "description": "Fetch a user by accountId/email",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-users/#api-rest-api-3-user-get",
        "scope": "users",
    },
    "status_list": {
        "method": "GET",
        "path": "/rest/api/3/status",
        "description": "List configured workflow statuses",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-statuses/#api-rest-api-3-status-get",
        "scope": "statuses",
    },
    "priority_list": {
        "method": "GET",
        "path": "/rest/api/3/priority",
        "description": "List configured priorities",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-priorities/#api-rest-api-3-priority-get",
        "scope": "priorities",
    },
    "issuetype_list": {
        "method": "GET",
        "path": "/rest/api/3/issuetype",
        "description": "List issue types (standard + sub-task)",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-types/#api-rest-api-3-issuetype-get",
        "scope": "issue_types",
    },
    "board_list": {
        "method": "GET",
        "path": "/rest/agile/1.0/board",
        "description": "List agile boards (Scrum/Kanban)",
        "docs": "https://developer.atlassian.com/cloud/jira/software/rest/api-group-board/#api-rest-agile-1-0-board-get",
        "scope": "boards",
    },
    "sprint_list": {
        "method": "GET",
        "path": "/rest/agile/1.0/board/{boardId}/sprint",
        "description": "List sprints for a board",
        "docs": "https://developer.atlassian.com/cloud/jira/software/rest/api-group-sprint/#api-agile-1-0-board-boardid-sprint-get",
        "scope": "sprints",
    },
    "issue_comments": {
        "method": "GET",
        "path": "/rest/api/3/issue/{issueIdOrKey}/comment",
        "description": "List all comments on an issue",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-comments/#api-rest-api-3-issue-issueidorkey-comment-get",
        "scope": "comments",
    },
    "issue_worklogs": {
        "method": "GET",
        "path": "/rest/api/3/issue/{issueIdOrKey}/worklog",
        "description": "Retrieve worklogs recorded against an issue",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-worklogs/#api-rest-api-3-issue-issueidorkey-worklog-get",
        "scope": "worklogs",
    },
}

JIRA_DATASET_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "jira.projects": {
        "name": "Jira Projects",
        "entity": "projects",
        "description": "Projects visible to the configured credentials.",
        "static_fields": [
            {"name": "projectKey", "data_type": "STRING", "nullable": False, "comment": "Project key (e.g. ENG)."},
            {"name": "name", "data_type": "STRING", "nullable": False},
            {"name": "projectType", "data_type": "STRING", "nullable": True},
            {"name": "lead", "data_type": "STRING", "nullable": True, "comment": "Display name for the project lead."},
            {"name": "url", "data_type": "STRING", "nullable": True, "comment": "Project browse URL."},
            {"name": "description", "data_type": "STRING", "nullable": True},
        ],
        "api_keys": ["project_search", "project_detail", "project_roles", "project_components"],
        "ingestion": {
            "enabled": True,
            "unit_id": "jira.projects",
            "display_name": "Projects",
            "description": "Catalog of Jira projects (key, name, type, lead).",
            "supports_incremental": False,
            "default_policy": None,
            "handler": "projects",
        },
    },
    "jira.issues": {
        "name": "Jira Issues",
        "entity": "issues",
        "description": "Work items synchronized from Jira (issues, epics, tasks, subtasks).",
        "static_fields": [
            {"name": "issueKey", "data_type": "STRING", "nullable": False},
            {"name": "summary", "data_type": "STRING", "nullable": True},
            {"name": "status", "data_type": "STRING", "nullable": True},
            {"name": "projectKey", "data_type": "STRING", "nullable": False},
            {"name": "issueType", "data_type": "STRING", "nullable": True},
            {"name": "assignee", "data_type": "STRING", "nullable": True},
            {"name": "reporter", "data_type": "STRING", "nullable": True},
            {"name": "priority", "data_type": "STRING", "nullable": True},
            {"name": "updatedAt", "data_type": "TIMESTAMP", "nullable": True},
            {"name": "createdAt", "data_type": "TIMESTAMP", "nullable": True},
        ],
        "dynamic_fields_source": "issue_fields",
        "api_keys": ["issue_search", "issue_detail", "issue_transitions", "field_catalog"],
        "ingestion": {
            "enabled": True,
            "unit_id": "jira.issues",
            "display_name": "Issues",
            "description": "Incremental sync of Jira issues (epics/tasks/subtasks).",
            "supports_incremental": True,
            "default_policy": {"cursor": "fields.updated"},
            "handler": "issues",
        },
    },
    "jira.users": {
        "name": "Jira Users",
        "entity": "users",
        "description": "Directory of Jira users referenced by work items.",
        "static_fields": [
            {"name": "accountId", "data_type": "STRING", "nullable": False},
            {"name": "displayName", "data_type": "STRING", "nullable": False},
            {"name": "email", "data_type": "STRING", "nullable": True},
            {"name": "timeZone", "data_type": "STRING", "nullable": True},
            {"name": "active", "data_type": "BOOLEAN", "nullable": True},
        ],
        "api_keys": ["user_search", "user_detail"],
        "ingestion": {
            "enabled": True,
            "unit_id": "jira.users",
            "display_name": "Users",
            "description": "Directory of Jira users referenced in issues/projects.",
            "supports_incremental": False,
            "default_policy": None,
            "handler": "users",
        },
    },
    "jira.issue_types": {
        "name": "Jira Issue Types",
        "entity": "issue_types",
        "description": "Catalog of configured Jira issue types (including custom hierarchies).",
        "static_fields": [
            {"name": "typeId", "data_type": "STRING", "nullable": False},
            {"name": "name", "data_type": "STRING", "nullable": False},
            {"name": "hierarchyLevel", "data_type": "INTEGER", "nullable": True},
            {"name": "subtask", "data_type": "BOOLEAN", "nullable": True},
            {"name": "description", "data_type": "STRING", "nullable": True},
            {"name": "avatarUrl", "data_type": "STRING", "nullable": True},
        ],
        "value_source": "issue_types",
        "api_keys": ["issuetype_list"],
    },
    "jira.statuses": {
        "name": "Jira Statuses",
        "entity": "statuses",
        "description": "Workflow statuses available to the Jira tenant.",
        "static_fields": [
            {"name": "statusId", "data_type": "STRING", "nullable": False},
            {"name": "name", "data_type": "STRING", "nullable": False},
            {"name": "category", "data_type": "STRING", "nullable": True},
            {"name": "categoryKey", "data_type": "STRING", "nullable": True},
            {"name": "categoryColor", "data_type": "STRING", "nullable": True},
            {"name": "description", "data_type": "STRING", "nullable": True},
        ],
        "value_source": "statuses",
        "api_keys": ["status_list"],
    },
    "jira.priorities": {
        "name": "Jira Priorities",
        "entity": "priorities",
        "description": "Priority levels configured in Jira.",
        "static_fields": [
            {"name": "priorityId", "data_type": "STRING", "nullable": False},
            {"name": "name", "data_type": "STRING", "nullable": False},
            {"name": "description", "data_type": "STRING", "nullable": True},
            {"name": "color", "data_type": "STRING", "nullable": True},
        ],
        "value_source": "priorities",
        "api_keys": ["priority_list"],
    },
    "jira.api_surface": {
        "name": "Jira API Surface",
        "entity": "api_surface",
        "description": "Inventory of REST APIs leveraged by Nucleus for Jira metadata + ingestion.",
        "static_fields": [
            {"name": "method", "data_type": "STRING", "nullable": False},
            {"name": "path", "data_type": "STRING", "nullable": False},
            {"name": "scope", "data_type": "STRING", "nullable": True},
            {"name": "description", "data_type": "STRING", "nullable": True},
            {"name": "docUrl", "data_type": "STRING", "nullable": True},
        ],
        "value_source": "api_catalog",
        "api_keys": [
            "project_search",
            "project_detail",
            "project_roles",
            "project_components",
            "issue_search",
            "issue_detail",
            "issue_transitions",
            "field_catalog",
            "user_search",
            "user_detail",
            "status_list",
            "priority_list",
            "issuetype_list",
            "board_list",
            "sprint_list",
            "issue_comments",
            "issue_worklogs",
        ],
    },
    "jira.comments": {
        "name": "Jira Comments",
        "entity": "comments",
        "description": "User conversations/comments attached to Jira issues.",
        "static_fields": [
            {"name": "commentId", "data_type": "STRING", "nullable": False},
            {"name": "issueKey", "data_type": "STRING", "nullable": False},
            {"name": "author", "data_type": "STRING", "nullable": True},
            {"name": "body", "data_type": "STRING", "nullable": True},
            {"name": "createdAt", "data_type": "TIMESTAMP", "nullable": True},
            {"name": "updatedAt", "data_type": "TIMESTAMP", "nullable": True},
        ],
        "api_keys": ["issue_comments"],
    },
    "jira.worklogs": {
        "name": "Jira Worklogs",
        "entity": "worklogs",
        "description": "Time tracking entries recorded against issues.",
        "static_fields": [
            {"name": "worklogId", "data_type": "STRING", "nullable": False},
            {"name": "issueKey", "data_type": "STRING", "nullable": False},
            {"name": "author", "data_type": "STRING", "nullable": True},
            {"name": "timeSpentSeconds", "data_type": "INTEGER", "nullable": True},
            {"name": "startedAt", "data_type": "TIMESTAMP", "nullable": True},
            {"name": "updatedAt", "data_type": "TIMESTAMP", "nullable": True},
        ],
        "api_keys": ["issue_worklogs"],
    },
}

__all__ = ["JIRA_API_LIBRARY", "JIRA_DATASET_DEFINITIONS"]
