// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/ucl.proto

package uclpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTemplatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by endpoint family (JDBC, HTTP, STREAM)
	Family        string `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_proto_ucl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{0}
}

func (x *ListTemplatesRequest) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*EndpointTemplate    `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_proto_ucl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{1}
}

func (x *ListTemplatesResponse) GetTemplates() []*EndpointTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type EndpointTemplate struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Family      string                 `protobuf:"bytes,2,opt,name=family,proto3" json:"family,omitempty"`
	DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Vendor      string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Fields      []*FieldDescriptor     `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	Categories  []string               `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	// New fields for full Python CLI parity
	Domain            string            `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	Protocols         []string          `protobuf:"bytes,9,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Versions          []string          `protobuf:"bytes,10,rep,name=versions,proto3" json:"versions,omitempty"`
	DefaultPort       int32             `protobuf:"varint,11,opt,name=default_port,json=defaultPort,proto3" json:"default_port,omitempty"`
	Driver            string            `protobuf:"bytes,12,opt,name=driver,proto3" json:"driver,omitempty"`
	DocsUrl           string            `protobuf:"bytes,13,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`
	AgentPrompt       string            `protobuf:"bytes,14,opt,name=agent_prompt,json=agentPrompt,proto3" json:"agent_prompt,omitempty"`
	DefaultLabels     []string          `protobuf:"bytes,15,rep,name=default_labels,json=defaultLabels,proto3" json:"default_labels,omitempty"`
	SampleConfig      map[string]string `protobuf:"bytes,16,rep,name=sample_config,json=sampleConfig,proto3" json:"sample_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Connection        map[string]string `protobuf:"bytes,17,rep,name=connection,proto3" json:"connection,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Probing           map[string]string `protobuf:"bytes,18,rep,name=probing,proto3" json:"probing,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Extras            map[string]string `protobuf:"bytes,19,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities      *Capabilities     `protobuf:"bytes,20,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	DescriptorVersion string            `protobuf:"bytes,21,opt,name=descriptor_version,json=descriptorVersion,proto3" json:"descriptor_version,omitempty"`
	MinVersion        string            `protobuf:"bytes,22,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MaxVersion        string            `protobuf:"bytes,23,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EndpointTemplate) Reset() {
	*x = EndpointTemplate{}
	mi := &file_proto_ucl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointTemplate) ProtoMessage() {}

func (x *EndpointTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointTemplate.ProtoReflect.Descriptor instead.
func (*EndpointTemplate) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EndpointTemplate) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *EndpointTemplate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EndpointTemplate) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *EndpointTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EndpointTemplate) GetFields() []*FieldDescriptor {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *EndpointTemplate) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *EndpointTemplate) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *EndpointTemplate) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *EndpointTemplate) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *EndpointTemplate) GetDefaultPort() int32 {
	if x != nil {
		return x.DefaultPort
	}
	return 0
}

func (x *EndpointTemplate) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *EndpointTemplate) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *EndpointTemplate) GetAgentPrompt() string {
	if x != nil {
		return x.AgentPrompt
	}
	return ""
}

func (x *EndpointTemplate) GetDefaultLabels() []string {
	if x != nil {
		return x.DefaultLabels
	}
	return nil
}

func (x *EndpointTemplate) GetSampleConfig() map[string]string {
	if x != nil {
		return x.SampleConfig
	}
	return nil
}

func (x *EndpointTemplate) GetConnection() map[string]string {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *EndpointTemplate) GetProbing() map[string]string {
	if x != nil {
		return x.Probing
	}
	return nil
}

func (x *EndpointTemplate) GetExtras() map[string]string {
	if x != nil {
		return x.Extras
	}
	return nil
}

func (x *EndpointTemplate) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *EndpointTemplate) GetDescriptorVersion() string {
	if x != nil {
		return x.DescriptorVersion
	}
	return ""
}

func (x *EndpointTemplate) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *EndpointTemplate) GetMaxVersion() string {
	if x != nil {
		return x.MaxVersion
	}
	return ""
}

// Capabilities describes what the endpoint supports
type Capabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SupportsFull        bool                   `protobuf:"varint,1,opt,name=supports_full,json=supportsFull,proto3" json:"supports_full,omitempty"`
	SupportsIncremental bool                   `protobuf:"varint,2,opt,name=supports_incremental,json=supportsIncremental,proto3" json:"supports_incremental,omitempty"`
	SupportsCountProbe  bool                   `protobuf:"varint,3,opt,name=supports_count_probe,json=supportsCountProbe,proto3" json:"supports_count_probe,omitempty"`
	SupportsPreview     bool                   `protobuf:"varint,4,opt,name=supports_preview,json=supportsPreview,proto3" json:"supports_preview,omitempty"`
	SupportsMetadata    bool                   `protobuf:"varint,5,opt,name=supports_metadata,json=supportsMetadata,proto3" json:"supports_metadata,omitempty"`
	DefaultFetchSize    int32                  `protobuf:"varint,6,opt,name=default_fetch_size,json=defaultFetchSize,proto3" json:"default_fetch_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_proto_ucl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{3}
}

func (x *Capabilities) GetSupportsFull() bool {
	if x != nil {
		return x.SupportsFull
	}
	return false
}

func (x *Capabilities) GetSupportsIncremental() bool {
	if x != nil {
		return x.SupportsIncremental
	}
	return false
}

func (x *Capabilities) GetSupportsCountProbe() bool {
	if x != nil {
		return x.SupportsCountProbe
	}
	return false
}

func (x *Capabilities) GetSupportsPreview() bool {
	if x != nil {
		return x.SupportsPreview
	}
	return false
}

func (x *Capabilities) GetSupportsMetadata() bool {
	if x != nil {
		return x.SupportsMetadata
	}
	return false
}

func (x *Capabilities) GetDefaultFetchSize() int32 {
	if x != nil {
		return x.DefaultFetchSize
	}
	return 0
}

type FieldDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // string, number, boolean, secret
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Options       []string               `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"` // For enum fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDescriptor) Reset() {
	*x = FieldDescriptor{}
	mi := &file_proto_ucl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDescriptor) ProtoMessage() {}

func (x *FieldDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDescriptor.ProtoReflect.Descriptor instead.
func (*FieldDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{4}
}

func (x *FieldDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldDescriptor) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FieldDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldDescriptor) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldDescriptor) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *FieldDescriptor) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type BuildConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildConfigRequest) Reset() {
	*x = BuildConfigRequest{}
	mi := &file_proto_ucl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildConfigRequest) ProtoMessage() {}

func (x *BuildConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildConfigRequest.ProtoReflect.Descriptor instead.
func (*BuildConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{5}
}

func (x *BuildConfigRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *BuildConfigRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *BuildConfigRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type BuildConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConnectionUrl string                 `protobuf:"bytes,3,opt,name=connection_url,json=connectionUrl,proto3" json:"connection_url,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildConfigResponse) Reset() {
	*x = BuildConfigResponse{}
	mi := &file_proto_ucl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildConfigResponse) ProtoMessage() {}

func (x *BuildConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildConfigResponse.ProtoReflect.Descriptor instead.
func (*BuildConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{6}
}

func (x *BuildConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *BuildConfigResponse) GetConnectionUrl() string {
	if x != nil {
		return x.ConnectionUrl
	}
	return ""
}

func (x *BuildConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	mi := &file_proto_ucl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{7}
}

func (x *TestConnectionRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TestConnectionRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type TestConnectionResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Success   bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message   string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	LatencyMs int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// New fields for full Python CLI parity
	DetectedVersion string            `protobuf:"bytes,5,opt,name=detected_version,json=detectedVersion,proto3" json:"detected_version,omitempty"`
	Capabilities    []string          `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Details         map[string]string `protobuf:"bytes,7,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	mi := &file_proto_ucl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{8}
}

func (x *TestConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestConnectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TestConnectionResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TestConnectionResponse) GetDetectedVersion() string {
	if x != nil {
		return x.DetectedVersion
	}
	return ""
}

func (x *TestConnectionResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *TestConnectionResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_proto_ucl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateConfigRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ValidateConfigRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_proto_ucl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateConfigResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ListDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsRequest) Reset() {
	*x = ListDatasetsRequest{}
	mi := &file_proto_ucl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsRequest) ProtoMessage() {}

func (x *ListDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{11}
}

func (x *ListDatasetsRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ListDatasetsRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ListDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []*Dataset             `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsResponse) Reset() {
	*x = ListDatasetsResponse{}
	mi := &file_proto_ucl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsResponse) ProtoMessage() {}

func (x *ListDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{12}
}

func (x *ListDatasetsResponse) GetDatasets() []*Dataset {
	if x != nil {
		return x.Datasets
	}
	return nil
}

// CODEX FIX: Aligned with endpoint.Dataset - includes all fields
type Dataset struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Kind                string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // "table", "view", "stream", "topic"
	SupportsIncremental bool                   `protobuf:"varint,5,opt,name=supports_incremental,json=supportsIncremental,proto3" json:"supports_incremental,omitempty"`
	CdmModelId          string                 `protobuf:"bytes,6,opt,name=cdm_model_id,json=cdmModelId,proto3" json:"cdm_model_id,omitempty"`                    // e.g., "cdm.work.item"
	IngestionStrategy   string                 `protobuf:"bytes,7,opt,name=ingestion_strategy,json=ingestionStrategy,proto3" json:"ingestion_strategy,omitempty"` // "full", "scd1", "cdc"
	IncrementalColumn   string                 `protobuf:"bytes,8,opt,name=incremental_column,json=incrementalColumn,proto3" json:"incremental_column,omitempty"`
	IncrementalLiteral  string                 `protobuf:"bytes,9,opt,name=incremental_literal,json=incrementalLiteral,proto3" json:"incremental_literal,omitempty"` // "timestamp", "epoch"
	PrimaryKeys         []string               `protobuf:"bytes,10,rep,name=primary_keys,json=primaryKeys,proto3" json:"primary_keys,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	mi := &file_proto_ucl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{13}
}

func (x *Dataset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dataset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dataset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dataset) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Dataset) GetSupportsIncremental() bool {
	if x != nil {
		return x.SupportsIncremental
	}
	return false
}

func (x *Dataset) GetCdmModelId() string {
	if x != nil {
		return x.CdmModelId
	}
	return ""
}

func (x *Dataset) GetIngestionStrategy() string {
	if x != nil {
		return x.IngestionStrategy
	}
	return ""
}

func (x *Dataset) GetIncrementalColumn() string {
	if x != nil {
		return x.IncrementalColumn
	}
	return ""
}

func (x *Dataset) GetIncrementalLiteral() string {
	if x != nil {
		return x.IncrementalLiteral
	}
	return ""
}

func (x *Dataset) GetPrimaryKeys() []string {
	if x != nil {
		return x.PrimaryKeys
	}
	return nil
}

func (x *Dataset) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_proto_ucl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{14}
}

func (x *GetSchemaRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *GetSchemaRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *GetSchemaRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*SchemaField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_proto_ucl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{15}
}

func (x *GetSchemaResponse) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// CODEX FIX: Aligned with endpoint.FieldDefinition - includes all fields
type SchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	IsPrimaryKey  bool                   `protobuf:"varint,4,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Precision     int32                  `protobuf:"varint,6,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale         int32                  `protobuf:"varint,7,opt,name=scale,proto3" json:"scale,omitempty"`
	Length        int32                  `protobuf:"varint,8,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	mi := &file_proto_ucl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ucl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_proto_ucl_proto_rawDescGZIP(), []int{16}
}

func (x *SchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SchemaField) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *SchemaField) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

func (x *SchemaField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemaField) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *SchemaField) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *SchemaField) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_proto_ucl_proto protoreflect.FileDescriptor

const file_proto_ucl_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/ucl.proto\x12\x06ucl.v1\".\n" +
	"\x14ListTemplatesRequest\x12\x16\n" +
	"\x06family\x18\x01 \x01(\tR\x06family\"O\n" +
	"\x15ListTemplatesResponse\x126\n" +
	"\ttemplates\x18\x01 \x03(\v2\x18.ucl.v1.EndpointTemplateR\ttemplates\"\x96\t\n" +
	"\x10EndpointTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06family\x18\x02 \x01(\tR\x06family\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12/\n" +
	"\x06fields\x18\x06 \x03(\v2\x17.ucl.v1.FieldDescriptorR\x06fields\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\x12\x1c\n" +
	"\tprotocols\x18\t \x03(\tR\tprotocols\x12\x1a\n" +
	"\bversions\x18\n" +
	" \x03(\tR\bversions\x12!\n" +
	"\fdefault_port\x18\v \x01(\x05R\vdefaultPort\x12\x16\n" +
	"\x06driver\x18\f \x01(\tR\x06driver\x12\x19\n" +
	"\bdocs_url\x18\r \x01(\tR\adocsUrl\x12!\n" +
	"\fagent_prompt\x18\x0e \x01(\tR\vagentPrompt\x12%\n" +
	"\x0edefault_labels\x18\x0f \x03(\tR\rdefaultLabels\x12O\n" +
	"\rsample_config\x18\x10 \x03(\v2*.ucl.v1.EndpointTemplate.SampleConfigEntryR\fsampleConfig\x12H\n" +
	"\n" +
	"connection\x18\x11 \x03(\v2(.ucl.v1.EndpointTemplate.ConnectionEntryR\n" +
	"connection\x12?\n" +
	"\aprobing\x18\x12 \x03(\v2%.ucl.v1.EndpointTemplate.ProbingEntryR\aprobing\x12<\n" +
	"\x06extras\x18\x13 \x03(\v2$.ucl.v1.EndpointTemplate.ExtrasEntryR\x06extras\x128\n" +
	"\fcapabilities\x18\x14 \x01(\v2\x14.ucl.v1.CapabilitiesR\fcapabilities\x12-\n" +
	"\x12descriptor_version\x18\x15 \x01(\tR\x11descriptorVersion\x12\x1f\n" +
	"\vmin_version\x18\x16 \x01(\tR\n" +
	"minVersion\x12\x1f\n" +
	"\vmax_version\x18\x17 \x01(\tR\n" +
	"maxVersion\x1a?\n" +
	"\x11SampleConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fConnectionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fProbingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"\fCapabilities\x12#\n" +
	"\rsupports_full\x18\x01 \x01(\bR\fsupportsFull\x121\n" +
	"\x14supports_incremental\x18\x02 \x01(\bR\x13supportsIncremental\x120\n" +
	"\x14supports_count_probe\x18\x03 \x01(\bR\x12supportsCountProbe\x12)\n" +
	"\x10supports_preview\x18\x04 \x01(\bR\x0fsupportsPreview\x12+\n" +
	"\x11supports_metadata\x18\x05 \x01(\bR\x10supportsMetadata\x12,\n" +
	"\x12default_fetch_size\x18\x06 \x01(\x05R\x10defaultFetchSize\"\xcc\x01\n" +
	"\x0fFieldDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x06 \x01(\tR\fdefaultValue\x12\x18\n" +
	"\aoptions\x18\a \x03(\tR\aoptions\"\xd8\x01\n" +
	"\x12BuildConfigRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12J\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2*.ucl.v1.BuildConfigRequest.ParametersEntryR\n" +
	"parameters\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x13BuildConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12?\n" +
	"\x06config\x18\x02 \x03(\v2'.ucl.v1.BuildConfigResponse.ConfigEntryR\x06config\x12%\n" +
	"\x0econnection_url\x18\x03 \x01(\tR\rconnectionUrl\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\x15TestConnectionRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12M\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2-.ucl.v1.TestConnectionRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x02\n" +
	"\x16TestConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12)\n" +
	"\x10detected_version\x18\x05 \x01(\tR\x0fdetectedVersion\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12E\n" +
	"\adetails\x18\a \x03(\v2+.ucl.v1.TestConnectionResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x15ValidateConfigRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12A\n" +
	"\x06config\x18\x02 \x03(\v2).ucl.v1.ValidateConfigRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"\xb2\x01\n" +
	"\x13ListDatasetsRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12?\n" +
	"\x06config\x18\x02 \x03(\v2'.ucl.v1.ListDatasetsRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x14ListDatasetsResponse\x12+\n" +
	"\bdatasets\x18\x01 \x03(\v2\x0f.ucl.v1.DatasetR\bdatasets\"\xe2\x03\n" +
	"\aDataset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x121\n" +
	"\x14supports_incremental\x18\x05 \x01(\bR\x13supportsIncremental\x12 \n" +
	"\fcdm_model_id\x18\x06 \x01(\tR\n" +
	"cdmModelId\x12-\n" +
	"\x12ingestion_strategy\x18\a \x01(\tR\x11ingestionStrategy\x12-\n" +
	"\x12incremental_column\x18\b \x01(\tR\x11incrementalColumn\x12/\n" +
	"\x13incremental_literal\x18\t \x01(\tR\x12incrementalLiteral\x12!\n" +
	"\fprimary_keys\x18\n" +
	" \x03(\tR\vprimaryKeys\x129\n" +
	"\bmetadata\x18\v \x03(\v2\x1d.ucl.v1.Dataset.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x10GetSchemaRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\x12<\n" +
	"\x06config\x18\x03 \x03(\v2$.ucl.v1.GetSchemaRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x11GetSchemaResponse\x12+\n" +
	"\x06fields\x18\x01 \x03(\v2\x13.ucl.v1.SchemaFieldR\x06fields\"\xe5\x01\n" +
	"\vSchemaField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12$\n" +
	"\x0eis_primary_key\x18\x04 \x01(\bR\fisPrimaryKey\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\tprecision\x18\x06 \x01(\x05R\tprecision\x12\x14\n" +
	"\x05scale\x18\a \x01(\x05R\x05scale\x12\x16\n" +
	"\x06length\x18\b \x01(\x05R\x06length2\xe9\x03\n" +
	"\n" +
	"UCLService\x12T\n" +
	"\x15ListEndpointTemplates\x12\x1c.ucl.v1.ListTemplatesRequest\x1a\x1d.ucl.v1.ListTemplatesResponse\x12N\n" +
	"\x13BuildEndpointConfig\x12\x1a.ucl.v1.BuildConfigRequest\x1a\x1b.ucl.v1.BuildConfigResponse\x12W\n" +
	"\x16TestEndpointConnection\x12\x1d.ucl.v1.TestConnectionRequest\x1a\x1e.ucl.v1.TestConnectionResponse\x12O\n" +
	"\x0eValidateConfig\x12\x1d.ucl.v1.ValidateConfigRequest\x1a\x1e.ucl.v1.ValidateConfigResponse\x12I\n" +
	"\fListDatasets\x12\x1b.ucl.v1.ListDatasetsRequest\x1a\x1c.ucl.v1.ListDatasetsResponse\x12@\n" +
	"\tGetSchema\x12\x18.ucl.v1.GetSchemaRequest\x1a\x19.ucl.v1.GetSchemaResponseB'Z%github.com/nucleus/ucl-core/pkg/uclpbb\x06proto3"

var (
	file_proto_ucl_proto_rawDescOnce sync.Once
	file_proto_ucl_proto_rawDescData []byte
)

func file_proto_ucl_proto_rawDescGZIP() []byte {
	file_proto_ucl_proto_rawDescOnce.Do(func() {
		file_proto_ucl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ucl_proto_rawDesc), len(file_proto_ucl_proto_rawDesc)))
	})
	return file_proto_ucl_proto_rawDescData
}

var file_proto_ucl_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_ucl_proto_goTypes = []any{
	(*ListTemplatesRequest)(nil),   // 0: ucl.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),  // 1: ucl.v1.ListTemplatesResponse
	(*EndpointTemplate)(nil),       // 2: ucl.v1.EndpointTemplate
	(*Capabilities)(nil),           // 3: ucl.v1.Capabilities
	(*FieldDescriptor)(nil),        // 4: ucl.v1.FieldDescriptor
	(*BuildConfigRequest)(nil),     // 5: ucl.v1.BuildConfigRequest
	(*BuildConfigResponse)(nil),    // 6: ucl.v1.BuildConfigResponse
	(*TestConnectionRequest)(nil),  // 7: ucl.v1.TestConnectionRequest
	(*TestConnectionResponse)(nil), // 8: ucl.v1.TestConnectionResponse
	(*ValidateConfigRequest)(nil),  // 9: ucl.v1.ValidateConfigRequest
	(*ValidateConfigResponse)(nil), // 10: ucl.v1.ValidateConfigResponse
	(*ListDatasetsRequest)(nil),    // 11: ucl.v1.ListDatasetsRequest
	(*ListDatasetsResponse)(nil),   // 12: ucl.v1.ListDatasetsResponse
	(*Dataset)(nil),                // 13: ucl.v1.Dataset
	(*GetSchemaRequest)(nil),       // 14: ucl.v1.GetSchemaRequest
	(*GetSchemaResponse)(nil),      // 15: ucl.v1.GetSchemaResponse
	(*SchemaField)(nil),            // 16: ucl.v1.SchemaField
	nil,                            // 17: ucl.v1.EndpointTemplate.SampleConfigEntry
	nil,                            // 18: ucl.v1.EndpointTemplate.ConnectionEntry
	nil,                            // 19: ucl.v1.EndpointTemplate.ProbingEntry
	nil,                            // 20: ucl.v1.EndpointTemplate.ExtrasEntry
	nil,                            // 21: ucl.v1.BuildConfigRequest.ParametersEntry
	nil,                            // 22: ucl.v1.BuildConfigResponse.ConfigEntry
	nil,                            // 23: ucl.v1.TestConnectionRequest.ParametersEntry
	nil,                            // 24: ucl.v1.TestConnectionResponse.DetailsEntry
	nil,                            // 25: ucl.v1.ValidateConfigRequest.ConfigEntry
	nil,                            // 26: ucl.v1.ListDatasetsRequest.ConfigEntry
	nil,                            // 27: ucl.v1.Dataset.MetadataEntry
	nil,                            // 28: ucl.v1.GetSchemaRequest.ConfigEntry
}
var file_proto_ucl_proto_depIdxs = []int32{
	2,  // 0: ucl.v1.ListTemplatesResponse.templates:type_name -> ucl.v1.EndpointTemplate
	4,  // 1: ucl.v1.EndpointTemplate.fields:type_name -> ucl.v1.FieldDescriptor
	17, // 2: ucl.v1.EndpointTemplate.sample_config:type_name -> ucl.v1.EndpointTemplate.SampleConfigEntry
	18, // 3: ucl.v1.EndpointTemplate.connection:type_name -> ucl.v1.EndpointTemplate.ConnectionEntry
	19, // 4: ucl.v1.EndpointTemplate.probing:type_name -> ucl.v1.EndpointTemplate.ProbingEntry
	20, // 5: ucl.v1.EndpointTemplate.extras:type_name -> ucl.v1.EndpointTemplate.ExtrasEntry
	3,  // 6: ucl.v1.EndpointTemplate.capabilities:type_name -> ucl.v1.Capabilities
	21, // 7: ucl.v1.BuildConfigRequest.parameters:type_name -> ucl.v1.BuildConfigRequest.ParametersEntry
	22, // 8: ucl.v1.BuildConfigResponse.config:type_name -> ucl.v1.BuildConfigResponse.ConfigEntry
	23, // 9: ucl.v1.TestConnectionRequest.parameters:type_name -> ucl.v1.TestConnectionRequest.ParametersEntry
	24, // 10: ucl.v1.TestConnectionResponse.details:type_name -> ucl.v1.TestConnectionResponse.DetailsEntry
	25, // 11: ucl.v1.ValidateConfigRequest.config:type_name -> ucl.v1.ValidateConfigRequest.ConfigEntry
	26, // 12: ucl.v1.ListDatasetsRequest.config:type_name -> ucl.v1.ListDatasetsRequest.ConfigEntry
	13, // 13: ucl.v1.ListDatasetsResponse.datasets:type_name -> ucl.v1.Dataset
	27, // 14: ucl.v1.Dataset.metadata:type_name -> ucl.v1.Dataset.MetadataEntry
	28, // 15: ucl.v1.GetSchemaRequest.config:type_name -> ucl.v1.GetSchemaRequest.ConfigEntry
	16, // 16: ucl.v1.GetSchemaResponse.fields:type_name -> ucl.v1.SchemaField
	0,  // 17: ucl.v1.UCLService.ListEndpointTemplates:input_type -> ucl.v1.ListTemplatesRequest
	5,  // 18: ucl.v1.UCLService.BuildEndpointConfig:input_type -> ucl.v1.BuildConfigRequest
	7,  // 19: ucl.v1.UCLService.TestEndpointConnection:input_type -> ucl.v1.TestConnectionRequest
	9,  // 20: ucl.v1.UCLService.ValidateConfig:input_type -> ucl.v1.ValidateConfigRequest
	11, // 21: ucl.v1.UCLService.ListDatasets:input_type -> ucl.v1.ListDatasetsRequest
	14, // 22: ucl.v1.UCLService.GetSchema:input_type -> ucl.v1.GetSchemaRequest
	1,  // 23: ucl.v1.UCLService.ListEndpointTemplates:output_type -> ucl.v1.ListTemplatesResponse
	6,  // 24: ucl.v1.UCLService.BuildEndpointConfig:output_type -> ucl.v1.BuildConfigResponse
	8,  // 25: ucl.v1.UCLService.TestEndpointConnection:output_type -> ucl.v1.TestConnectionResponse
	10, // 26: ucl.v1.UCLService.ValidateConfig:output_type -> ucl.v1.ValidateConfigResponse
	12, // 27: ucl.v1.UCLService.ListDatasets:output_type -> ucl.v1.ListDatasetsResponse
	15, // 28: ucl.v1.UCLService.GetSchema:output_type -> ucl.v1.GetSchemaResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_ucl_proto_init() }
func file_proto_ucl_proto_init() {
	if File_proto_ucl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ucl_proto_rawDesc), len(file_proto_ucl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ucl_proto_goTypes,
		DependencyIndexes: file_proto_ucl_proto_depIdxs,
		MessageInfos:      file_proto_ucl_proto_msgTypes,
	}.Build()
	File_proto_ucl_proto = out.File
	file_proto_ucl_proto_goTypes = nil
	file_proto_ucl_proto_depIdxs = nil
}
